# MET Database Cleaning - Milestone II

Very much a work in progress while we figure out what exactly we need out of the full dataset / what specific cleaning tasks we need to do

In [1]:
from country_name import determine_met_country_names
import pandas as pd
# import warnings
# warnings.filterwarnings('ignore')

Read in full dataset from MET github

In [16]:
met = pd.read_csv('https://media.githubusercontent.com/media/metmuseum/openaccess/refs/heads/master/MetObjects.csv')

/var/folders/cy/f_z2j2b90rl7q8vz6jzfv__00000gn/T/ipykernel_82296/2058581641.py:1: DtypeWarning: Columns (5,7,10,11,12,13,14,34,35,36,37,38,39,40,41,42,43,44,45,46) have mixed types. Specify dtype option on import or set low_memory=False.
  met = pd.read_csv('https://media.githubusercontent.com/media/metmuseum/openaccess/refs/heads/master/MetObjects.csv')

In [17]:
met

,Object Number,Is Highlight,Is Timeline Work,Is Public Domain,Object ID,Gallery Number,Department,AccessionYear,Object Name,Title,...,River,Classification,Rights and Reproduction,Link Resource,Object Wikidata URL,Metadata Date,Repository,Tags,Tags AAT URL,Tags Wikidata URL
0,1979.486.1,False,False,False,1,NaN,The American Wing,1979.0,Coin,One-dollar Liberty Head Coin,...,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/1,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
1,1980.264.5,False,False,False,2,NaN,The American Wing,1980.0,Coin,Ten-dollar Liberty Head Coin,...,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/2,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
2,67.265.9,False,False,False,3,NaN,The American Wing,1967.0,Coin,Two-and-a-Half Dollar Coin,...,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/3,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
3,67.265.10,False,False,False,4,NaN,The American Wing,1967.0,Coin,Two-and-a-Half Dollar Coin,...,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/4,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
4,67.265.11,False,False,False,5,NaN,The American Wing,1967.0,Coin,Two-and-a-Half Dollar Coin,...,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/5,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
484951,55.621.134,False,False,False,900605,NaN,Drawings and Prints,1955,Print,Holiday Card,...,NaN,Prints,NaN,http://www.metmuseum.org/art/collection/search...,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
484952,1977.646,False,False,False,900606,NaN,Drawings and Prints,1977,Print,Brooklyn Local,...,NaN,Prints,NaN,http://www.metmuseum.org/art/collection/search...,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
484953,33.40.1,False,False,False,900633,NaN,Drawings and Prints,1933,Print,Yesterday and Today,...,NaN,Prints,NaN,http://www.metmuseum.org/art/collection/search...,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
484954,170.1 C42,True,False,False,900717,NaN,The Libraries,NaN,NaN,"De la loi du contraste simultané des couleurs,...",...,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search...,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
484955,17.3.3457,False,False,False,900748,NaN,Drawings and Prints,1917,Print,Madison Square - Fifth Avenue and Broadway at ...,...,NaN,Prints,NaN,http://www.metmuseum.org/art/collection/search...,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN

Normalize columns names for ease of use

In [18]:
met = met.rename(columns={'Object ID':'object_id','Object Number': 'object_number', 'Is Highlight': 'is_highlight', 'Is Timeline Work': 'is_timeline_work', 'Is Public Domain': 'is_public_domain',
       'Gallery Number':'gallery_number', 'Department':'department', 'AccessionYear':'accession_year', 'Object Name':'object_name', 'Title':'title',
       'Culture':'culture', 'Period': 'period', 'Dynasty': 'dynasty', 'Reign': 'reign', 'Portfolio': 'portfolio', 'Constituent ID': 'constituent_id',
       'Artist Role':'artist_role', 'Artist Prefix':'artist_prefix', 'Artist Display Name':'artist_display_name',
       'Artist Display Bio': 'artist_display_bio', 'Artist Suffix':'artist_suffix', 'Artist Alpha Sort':'artist_alpha_sort',
       'Artist Nationality':'artist_nationality', 'Artist Begin Date':'artist_begin_date', 'Artist End Date':'artist_end_date',
       'Artist Gender':'artist_gender', 'Artist ULAN URL':'artist_ulan_url', 'Artist Wikidata URL':'artist_wikidata_url',
       'Object Date':'object_date', 'Object Begin Date':'object_begin_date', 'Object End Date':'object_end_date', 'Medium':'medium',
       'Dimensions':'dimensions', 'Credit Line':'credit_line', 'Geography Type':'geography_type', 'City':'city', 'State':'state',
       'County':'county', 'Country':'country', 'Region':'region', 'Subregion':'subregion', 'Locale':'locale', 'Locus':'locus',
       'Excavation':'excavation', 'River':'river', 'Classification':'classification', 'Rights and Reproduction':'rights_and_reproduction',
       'Link Resource':'link_resource', 'Object Wikidata URL':'object_wikidata_url', 'Metadata Date':'metadata_date', 'Repository':'repository',
       'Tags':'tags', 'Tags AAT URL':'tags_aat_url', 'Tags Wikidata URL':'tags_wikidata_url'})
met.set_index('object_id', inplace=True)

In [19]:
met = determine_met_country_names(met, "../data/helper/countries.csv")

In [20]:
met['is_significant'] = met['is_timeline_work'] | met['is_highlight']

In [21]:
met = met.replace({'object_date':{"–":"-", " ":"", "ca.":"", "before":"","after":"","edition":"", "()":"","probably":"", "Probably":"","early":"", "late":"", r'\?':"",
                                  "20thcentury":"1900", "19thcentury":"1800", "18thcentury":"1700", "17thcentury":"1600", "16thcentury":"1500",
                                  "15thcentury":"1400", "14thcentury":"1300", "13thcentury":"1200", "12thcentury":"1100", "11thcentury":"1000",
                                  "10thcentury":"1400", "9thcentury":"1300", "8thcentury":"1200", "7thcentury":"1100", "6thcentury":"1000",
                                  "5thcentury":"400", "4thcentury":"300", "3rdcentury":"200", "2ndcentury":"100", "1stcentury":"0000",
                                  "by":"", "or":"-",
                                  
                                  }}, regex=True)

In [22]:
met['extracted_date'] = met['object_date'].str.findall(r'\d{4}').str[0]

In [25]:
met['artist_gender'] = met['artist_gender'].replace(False, "0")
met['artist_gender'] = met['artist_gender'].replace(True, "1")
# = met.where(met['artist_gender'].isna(), "1", "0")
# met['artist_gender'] = met.where(~met['artist_gender'].isna(), "0")

In [69]:
df = met.copy()
# df = df.dropna(subset='accession_year')

In [ ]:
met.loc[:,'tags'] = met['tags'].str.split(pat="|")

In [70]:
# df['accession_year'] = df['accession_year'].astype(str)
df['accession_year'].astype(str).str.findall(r'\d{4}').str[0]

object_id
1         1979
2         1980
3         1967
4         1967
5         1967
          ...
900605    1955
900606    1977
900633    1933
900717     NaN
900748    1917
Name: accession_year, Length: 484956, dtype: object

In [61]:
df['tags'].dropna()

object_id
7                            [Birds, Coins]
8                   [Eagles, Men, Profiles]
33        [Men, Abraham Lincoln, Portraits]
34                      [Landscapes, Boats]
35          [Animals, Garlands, Birds, Men]
                        ...
900139                          [Billiards]
900144                     [Horses, Sports]
900271                               [Cats]
900272                               [Cats]
900273                               [Owls]
Name: tags, Length: 192455, dtype: object

Drop unnecessary columns (dropped columns listed in comments)

In [9]:
met = met[['is_significant', 'is_public_domain',
        'department', 'accession_year', 'object_name',
       'title', 'culture', 'portfolio',
        'artist_display_name', 
       'artist_nationality', 
       'artist_gender', 'mapped_country',
       'extracted_date',  'medium', 'tags']]

# 'artist_display_bio','dimensions','object_number','credit_line', 'geography_type', 'city', 'state','county', 'locale', 'locus','excavation', 'river',
# 'tags_aat_url', 'tags_wikidata_url', 'object_wikidata_url', 'metadata_date', 'link_resource', 'object_begin_date', 'object_date',
# 'object_end_date', 'artist_ulan_url', 'artist_wikidata_url', 'artist_alpha_sort', 'gallery_number',        'classification', 'rights_and_reproduction',
# 'repository', 'constituent_id', 'artist_role', 'artist_prefix', 'period', 'dynasty', 'reign', 'artist_begin_date', 'artist_end_date', 'artist_suffix',

combine all columns that have strings into one, then apply nlp preprocessing

department, object name, title, culture,

In [10]:
met.head()

,is_significant,is_public_domain,department,accession_year,object_name,title,culture,portfolio,artist_display_name,artist_nationality,artist_gender,mapped_country,extracted_date,medium,tags
object_id,,,,,,,,,,,,,,,
1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

###

next steps: determine which columns we want to use to train our classifier (determine column independence, etc)

###